### PR TITLE
Update the project to just use sh

### PR DESCRIPTION
**Pull request by ElGreetly**
Removed: the python scripts replaced it with shell curl
Added: flag option to delete a project
Updated: README

### CODE REVIEW

**Comment by nelsonmestevao** [comment]
The pull request #4 is a much better approach than using just shell.

**Comment by ElGreetly** [comment]
> The pull request #4 is a much better approach than using just shell.

I do not know the principles that make you see mixed python with 3 imported libraries and bash better than just bash script for a small task like that.
- The start-up time of a bash shell script is 2.8 milliseconds while that of python is 11.1 milliseconds.
- Bash shell programming is the default terminal in most Linux distributions and thus it will always be faster in terms of performance.
- Bash Shell Scripting works flawlessly and fast when dealing with files copying, cloning disks, writing backup apps for networking, ftp servers, storing file inputs and accessing them later and transferring those outputs later on to something else with the help of pipe.
- Using many aliases is not also good as it's may override other aliases, more difficult to memories and much aliases that will be loaded to the terminal every time you fire a new one of course just 2 will not affect much but after a while, it will be crowded not clean.

on the other hand, I would say that python or mixed will be good dealing with more large projects or more complex projects as bash will be harder to read and maintain.

I hope you could give me your points maybe I could take benefits from them.

**Comment by nelsonmestevao** [comment]
> I hope you could give me your points maybe I could take benefits from them.

Yes, sure. 

First, I think bash is a great tool but not the best for this one, in my opinion. For instance, having your GitHub password on the script itself is not great because it makes harder for you to version control it and share it (so, I am in favour of the `.env` approach). You could probably solve this by using a tool like direnv.

Second, I think it is also more robust to use PyGithub with the GitHub API since it can change (and probably will) and I would not like to have to think about it. Also, your API calls are relying on you having  `curl` installed on your system which is not necessarily true. 

Those are the two main point for me to prefer the python approach. Regarding your points, it is also true that python comes in most Linux distributions. I don't really know about performance, but I do know that it is not the main selling points of bash or python. Anyway, as you said, it is a small task and for that reason, it doesn't really matter.

Keep in mind that is just my opinion. I am probably wrong.

**Comment by ElGreetly** [comment]
> Yes, sure.

Really appreciate your response for your first point you know it's very easy to add env variables to a bash script so I updated the project with the .env file.
for the second point, I agree with you the API may change put then you will need to update your lib as you may do for the 2 endpoints with the script.
about curl may not be installed I think if the distro has python probably it will have curl I could also add a check if it's there or not but I see it's not necessary.

Thank you <3

**Comment by nelsonmestevao** [comment]
No problem. 

My first suggestion was way too complicated but your change was super easy and clean. 

I also don't think it's really necessary to check if curl is installed 😛

**Pull request closed without merging**
